src/Export/Data/Entity/EntityFactory.php
src/Export/Data/Entity/VariantEntity.php
src/Resources/config/services.xml

Description:
Added a mechanism allowing user to tag specific `FieldInterface` implementations with a `factfinder.export.variant_field`. A service tagged in this way will be added to a pool of fields which should be exported on a variant level, which means the export will prefer the variant values instead of main articles
Tested with Shopware editions/versions:
6.3.5.1
Tested with PHP versions:
7.4

FFWEB-2012: Export custom fields from variants

---

.github/workflows/ci.yml
composer.json
spec/Export/Field/CategoryPathSpec.php
src/Export/Field/CategoryPath.php

- Description
Reworked category path export using builtin [CategoryBreadcrumbBuilder](https://github.com/shopware/platform/blob/v6.3.2.0/src/Core/Content/Category/Service/CategoryBreadcrumbBuilder.php) 
Filter out Category paths which not originate from main navigation category from active sales channel
Bump min Shopware6 compatible version to `6.3.2`
Tested with Shopware6 editions/versions:
6.3.5
Tested with PHP versions:
7.4

FFWEB-2026: Export category path only from sales channel stored in context

---

CHANGELOG.md
src/Communication/PushImportService.php
src/Config/BaseConfig.php
src/Config/Communication.php
src/Config/FtpConfig.php
src/Upload/UploadService.php

If you run export wit `-u` flag and other than default sales channel, then exported file will be uploaded to the FTP server with a name containing FACT-Finder channel configured for default channel, not the chosen one. Fix allows to pass sales channel id as a parameter to config functions in order to get stored values in a correct scope
6.4
7.4

FFWEB-2092: Fix naming export files during FTP upload

---

CHANGELOG.md
src/OmikronFactFinder.php

Custom Fields installed by the module shall have type 'bool', not 'switch' in order to work properly. This might be a Showpare6 bug but we need to keen on correctly working plugin first
6.4
7.4

FFWEB-2198 Fix ActiveSwitchers CustomFields

---

CHANGELOG.md
spec/Subscriber/CategoryViewSpec.php
src/OmikronFactFinder.php
src/Subscriber/CategoryView.php

Adds custom field for Category Entity which allows to set search-immediate on given category page
6.4
- Tested with PHP versions:
- 7.4

FFWEB-2195: set search immediate for category

---

CHANGELOG.md
src/Resources/views/storefront/components/factfinder/record-list.html.twig
src/Resources/views/storefront/element/cms-element-record-list.html.twig

The values `infinite-scrolling` and `infinite-debounce-delay` are passed incorrectly from the PageBuilder configuration to the template. In result `infinite-scrolling` is always enabled, even thought it should not, and `infinite-debounce-delay` is also enabled and rendered with incorrect value
6.4
8.0

FFWEB-2212: Fix page builder bug with infinite-scrolling

---

src/Export/Field/Price.php

[FFWEB-2214](https://jira.omikron.net/browse/FFWEB-2214)
- Description:
Customer reports that product export doesn't work correctly on shopware versions 6.4.4.0 and higher
6.4.3.1/6.4.5.0
7.4.20

FFWEB-2214: Add missing use statement to solve breaked feed export

---

CHANGELOG.md
spec/Export/Field/LayoutSpec.php
src/Export/ExportCategories.php
src/Export/Field/Deeplink.php
src/Export/Field/Layout.php
src/Internal/utils.php
src/Subscriber/CategoryPageSubscriber.php

- Add Layout column to CMS export
- 6.4.9
- 7.4

FFWEB-2443: Add Layout column to CMS export

---

.gitignore
CHANGELOG.md
src/Resources/views/storefront/components/factfinder/asn-group.html.twig
src/Resources/views/storefront/components/factfinder/asn.html.twig
src/Resources/views/storefront/element/cms-element-asn.html.twig
src/Subscriber/CategoryPageSubscriber.php

Hides the category filter on the category page. Using this filter while on the category page does not render the page. This leads to a situation where the fixed filter set in `ff-communication/category-page` will still match the category the user is on, but products rendered by the Web Components will be from different category
-  6.4.9
- 7.4
- 8.0

FFWEB-2125: Hide category filter on category page

---

CHANGELOG.md
src/Resources/config/services.xml

- fix `ImageUrl` does not export variants images as wrong association is used 
6.4.9999999.9999999 Developer Version
8.0

FFWEB-2745 Fix image url is not exported for variant

---

CHANGELOG.md
src/Resources/views/storefront/components/factfinder/recommendation.html.twig
src/Resources/views/storefront/components/factfinder/record-list-slider.html.twig
src/Resources/views/storefront/components/factfinder/similar-products.html.twig
src/Resources/views/storefront/page/product-detail/tabs.html.twig

initialize sliders on pdp only after the records are renderd
6.4.
6.4.10

FFWEB-2564: Delay slider initialization on pdp

---

CHANGELOG.md
spec/Subscriber/BeforeSendResponseEventSubscriberSpec.php
src/Cookie/CookieProvider.php
src/Resources/config/services.xml
src/Subscriber/BeforeSendResponseEventSubscriber.php

- FFWEB-2607
- Description:
- extended the cookie consent manager with cookies added in release [v3.3.2](https://github.com/FACT-Finder-Web-Components/shopware6-plugin/releases/tag/v3.3.2)
- 7.4

FFWEB-2607: decorate CookieProviderInterface

---

CHANGELOG.md
src/Resources/views/storefront/base.html.twig

- FFWEB-2620
- Description:
- remove `query` parameter from undesirable urls (not related with FACT-Finder)
- 7.4

FFWEB-2620: Remove query parameter from undesirable urls

---

CHANGELOG.md
spec/Subscriber/ConfigurationSubscriberSpec.php
src/Subscriber/ConfigurationSubscriber.php

- FFWEB-2635
- Description:
- Fix problem with missing page in ConfigurationSubscriber
- 7.4

FFWEB-2635: Fix problem with missing page in ConfigurationSubscriber

---

CHANGELOG.md
src/Communication/ClientBuilderConfigurator.php

- FFWEB-2641
- Description:
- Fix problem with missing server URL when SDK is activated for first time
- 7.4

FFWEB-2641: fix missing server url

---

src/Subscriber/CategoryPageResponseSubscriber.php

URL query parameter "p" must be translated to "page" for search against FF backend

#117 - query parameter "p" must be translated to "page"

---

CHANGELOG.md
composer.json
spec/Storefront/Controller/ResultControllerSpec.php
src/Config/FieldRoles.php
src/Export/Data/Entity/ProductEntity.php
src/Resources/app/storefront/src/plugin/asn-plugin.js
src/Resources/config/services.xml
src/Resources/views/storefront/base.html.twig
src/Storefront/Controller/ResultController.php
src/Subscriber/BeforeSendResponseEventSubscriber.php
src/Subscriber/CategoryPageResponseSubscriber.php
src/Subscriber/CategoryPageSubscriber.php
src/Subscriber/ConfigurationSubscriber.php
src/Subscriber/CustomerLoginEventSubscriber.php
src/Subscriber/CustomerLogoutEventSubscriber.php
src/Utilites/Ssr/Field/CategoryPath.php
src/Utilites/Ssr/PriceFormatter.php
src/Utilites/Ssr/SearchAdapter.php
src/Utilites/Ssr/Template/Engine.php
src/Utilites/Ssr/Template/Filter.php
src/Utilites/Ssr/Template/Loader.php
src/Utilites/Ssr/Template/RecordList.php
src/Utilites/Ssr/Template/StringLoader.php

- FFWEB-2524
- FFWEB-2647
- Description:
- SSR
- read fieldRoles using service and set default configuration as backup
- set SalesChannelId
- display navigation results when HTTP cache is enabled
- Fixed Uncaught TypeError: can't access property "find", t.path is undefined
- Replace FF_SEARCH_RESULT with empty string when page don't have to SSR
- add support for Mustache template engine
- set RequestStack as optional to avid fails for CLI-Commands
- combine masterValues with variantValues in search results
- prevent error when invalid chanel is set
- pass all parameters for category pages and search result
- query parameter "p" must be translated to "page"
- add SEO urls and link-rel-prev/next for pagination
- BeforeSendResponseEventSubscriber - fix Call to a member …

FFWEB-2524: SSR improvements

---

src/Subscriber/CategoryPageResponseSubscriber.php

#126 - only replace FF_SEARCH_RESULT if no real result will be rendered

---

src/Subscriber/CategoryPageSubscriber.php

- FFWEB-2659
- Description:
- Fix problem with missing attribute `category-page` in `ff-communication` element for Navigation Page
- 6.4.18.0
- 7.4
- 8.1

FFWEB-2659: add missing attribute `category-page`

---

CHANGELOG.md
src/Export/ExportCategories.php

- FFWEB-2668
- Description:
- Export only active categories
- 6.4.18.0
- 7.4
- 8.1

FFWEB-2668: Export only active categories

---

CHANGELOG.md
src/Resources/views/storefront/base.html.twig

- FFWEB-2667
- Description:
- Fix sorting for category page
- 6.4.18.0
- 7.4
- 8.1

FFWEB-2667 - Fix sorting for category page

---

CHANGELOG.md
src/Export/Field/PriceCurrency.php

- FFWEB-2691
- Description:
- Fix problem with PriceCurrency during export
- 6.4.20.0
- 8.2
- 7.4

FFWEB-2691: fix problem with PriceCurrency during export

---

src/Subscriber/CategoryPageResponseSubscriber.php

handling for error: Argument #1 ($categoryEntity) must be of type Shopware\Core\Content\Category\CategoryEntity, null given

error handling

---

CHANGELOG.md
README.md

fix Adding New Column to Feed example and use correct ProductEntity class in getCompatibleEntityTypes
Currently the example in the Readme doesn't work and confuses new devs.
fix `Adding New Column to Feed` example 
only docs changed
only docs changed

fix Adding New Column to Feed example

---

CHANGELOG.md
src/Command/RunPreprocessorCommand.php
src/DataAbstractionLayer/FeedPreprocessorEntryReader.php
src/Export/ExportProducts.php
src/Export/FeedPreprocessorEntryDefinition.php

- FFWEB-2707
- Description:
- Fix type for custom_fields and filter_attributes in FeedPreprocessorEntryDefinition
- Remove deprecations for EntityRepository and SalesChannelRepository
- 6.4.20.0
- 8.2
- 7.4

FFWEB-2707: Fix type for custom_fields and filter_attributes

---

src/Export/Filter/TextFilter.php

- FFWEB-2702
- Description:
- mb_convert_encoding is deprecated. Use htmlentities instead.
- 6.4.20.0
- 8.2
- 7.4

FFWEB-2705: Remove deprecations from TextFilter

---

CHANGELOG.md
src/Command/RunPreprocessorCommand.php
src/DataAbstractionLayer/FeedPreprocessorEntryReader.php
src/Export/ExportProducts.php

- FFWEB-2710
- Description:
- EntityRepositoryInterface and SalesChannelRepositoryInterface will be deleted in  Shopware v. 6.5 We will prepare special release for compatible with Shopware v. 6.5 soon.
- 6.4.20.0
- 8.2
- 7.4

FFWEB-2710: Backward compatibility for Shopware v. 6.4

---

CHANGELOG.md
src/Export/FeedPreprocessorEntryDefinition.php
src/Migration/Migration1689762417VariationKeyType.php

- Solves issue:  FFWEB-2765
- Description: Change type to LONGTEXT for column `variation_key` in table `factfinder_feed_preprocessor`
- Tested with Shopware6 editions/versions: 6.4.20
- Tested with PHP versions: 7.4, 8.2

FFWEB-2765: Change type for column variation_key

---

.gitignore
CHANGELOG.md
src/Command/DataExportCommand.php
src/Command/RunPreprocessorCommand.php
src/DataAbstractionLayer/FeedPreprocessorEntryReader.php
src/Export/ExportCategories.php
src/Export/ExportCmsPages.php
src/MessageQueue/FeedExportHandler.php
src/MessageQueue/RefreshExportCacheHandler.php
src/OmikronFactFinder.php
src/Resources/config/services.xml
src/Subscriber/CategoryPageResponseSubscriber.php
src/Subscriber/FeedPreprocessorEntrySubscriber.php
src/Subscriber/ProductIndexerSubscriber.php

- Solves issue: FFWEB-2779
- Description:  Replace missing Interfaces EntityRepositoryInterface SalesChannelRepositoryInterface and  in Shopware6.5.

FFWEB-2779: Replace missing Interfaces in Shopware6.5

---

src/Resources/app/storefront/src/scss/_asn.scss
src/Resources/app/storefront/src/scss/_searchbox.scss
src/Subscriber/BeforeSendResponseEventSubscriber.php

- Solves issue: FFWEB-2781
- Description: Migrate Bootstrap framework from v4 to v5

FFWEB-2781: Migrate Bootstrap framework from v4 to v5

---

CHANGELOG.md
src/Utilites/Ssr/Field/CategoryPath.php

- Solves issue: FFWEB-2803
- Description:  Error handling for empty category paths

FFWEB-2803: Error handling for empty category paths

---

src/Export/Filter/ExtendedTextFilter.php
src/Export/Filter/FilterInterface.php
src/Export/Filter/TextFilter.php
src/Utilites/Ssr/Template/Filter.php

error handling for error `Omikron\FactFinder\Shopware6\Export\Filter\TextFilter::filterValue(): Argument #1 ($value) must be of type string, null given`

error handling for usage of TextFilter with null value

---

CHANGELOG.md
README.md
src/Api/TestConnectionController.php
src/Resources/app/administration/src/module/configuration/component/test-api-connection/index.js
src/Resources/app/administration/src/module/configuration/component/test-api-connection/test-api-connection.html.twig
src/Resources/app/administration/src/module/configuration/component/test-api-connection/test-api-connection.scss
src/Resources/app/administration/src/module/configuration/index.js
src/Resources/app/administration/src/module/configuration/snippet/de-DE.json
src/Resources/app/administration/src/module/configuration/snippet/en-GB.json
src/Resources/config/config.xml
src/Resources/config/services.xml

- Solves issue: FFWEB-2799
- Description: Add small feature to test API connection by one btn click.

FFWEB-2799: Add test API connection btn

---

CHANGELOG.md
README.md
src/Api/TestConnectionController.php
src/Resources/app/administration/src/module/configuration/component/test-api-connection/index.js
src/Resources/app/administration/src/module/configuration/component/test-api-connection/test-api-connection.html.twig
src/Resources/app/administration/src/module/configuration/component/test-api-connection/test-api-connection.scss
src/Resources/app/administration/src/module/configuration/index.js
src/Resources/app/administration/src/module/configuration/snippet/de-DE.json
src/Resources/app/administration/src/module/configuration/snippet/en-GB.json
src/Resources/config/config.xml
src/Resources/config/services.xml

- Solves issue: FFWEB-2832
- Description: Add test API connection button

FFWEB-2832: Add test API connection button

---

CHANGELOG.md
src/Subscriber/ConfigurationSubscriber.php

- Solves issue:  FFWEB-2930
- Description:  Filter empty attributes for ff-communication component

FFWEB-2930: Filter empty attributes for ff-communication component

---

CHANGELOG.md
src/Cookie/CookieProvider.php
src/Resources/snippet/factfinder.de-DE.json
src/Resources/snippet/factfinder.en-GB.json

- Solves issue:  FFWEB-2955
- Description:Set FactFinder cookies as required in CookieConsentManager
- Tested with Shopware6 editions/versions: 6.4.20

FFWEB-2955: Set FactFinder cookies as required in CookieConsentManager

---

CHANGELOG.md
composer.json
phpstan.neon
src/DataAbstractionLayer/FeedPreprocessor.php
src/OmikronFactFinder.php
src/Subscriber/ConfigurationSubscriber.php

- Solves issue: FFWEB-2965
- Description: Add PHPStan for checking code quality

FFWEB-2965: Add PHPStan for checking code quality

---

CHANGELOG.md
src/Storefront/Controller/ResultController.php
src/Subscriber/CategoryPageResponseSubscriber.php
src/Utilites/Ssr/Exception/DetectRedirectCampaignException.php
src/Utilites/Ssr/Template/RecordList.php

- Solves issue: FFWEB-2975
- Description: Support Fact-Finder redirect campaigns for SSR

FFWEB-2975: Support Fact-Finder redirect campaigns for SSR

---

src/Communication/ClientBuilderConfigurator.php
src/Resources/config/config.xml

- Solves issue: FFWEB-2984
- Description: Add validation for plugin config
- Tested with PHP versions: 8.2

FFWEB-2984: Add validation for plugin config

---

src/FactFinder.php

Plugin uninstallation process
- Solves issue: FFWEB-2985
- Description: Plugin uninstallation process
- Tested with PHP versions: 8.2

FFWEB-2985: Plugin uninstallation process

---

src/Resources/app/administration/src/module/sw-cms/elements/asn/config/sw-cms-el-config-asn.html.twig
src/Resources/views/storefront/components/factfinder/asn.html.twig
src/Resources/views/storefront/components/factfinder/campaign-advisor.html.twig
src/Resources/views/storefront/layout/factfinder/suggest.html.twig
src/Resources/views/storefront/page/factfinder/result.html.twig

- Solves issue: FFWEB-2987
- Description: <hx> tags are forbidden in marketplace version. Change it to `<div class="h1">`

FFWEB-2987: Ged rid of <hx> tags from templates

---

src/Utilites/Ssr/Template/RecordList.php

... in searching so it also works if we use searching and rendering separated in our customization
In this PR
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/pull/169
we separated searching and rendering in 2 methods.
We use these 2 methods in our customizations (instead of just "getContent")
This PR
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/pull/187
this separation is ignored.
I moved this functionality into one of the separated methods, so it works for "getContent" as well as "searchResults"+"renderResults".
**Please note that the source and target branch must be `master` ([details](https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blo …

SSR: move handling for Redirect Campaigns
