FACT-Finder-Web-Components/shopware6-plugin

spec/Export/Field/PriceSpec.php, src/Command/ProductExportCommand.php, src/Export/Field/Price.php, src/Resources/config/services.xml
Product prices were not yet included in the export feed!
=> Export product prices

src/Command/ProductExportCommand.php
Currently if the shop has more then one saleschannel, you can not choose the saleschannel for which you want to export.
=> allow to configure the saleschannel in the product export command

spec/Export/Field/BrandSpec.php, spec/Export/Field/CategoryPathSpec.php, spec/Export/Field/CustomFieldsSpec.php, spec/Export/Field/DescriptionSpec.php, spec/Export/PropertyFormatterSpec.php, src/Command/ProductExportCommand.php, src/Export/Data/Entity/ProductEntity.php, src/Export/ExportProducts.php, src/Export/Field/Brand.php, src/Export/Field/CategoryPath.php, src/Export/Field/CustomFields.php, src/Export/Field/Description.php, src/Export/PropertyFormatter.php, src/Export/SalesChannelService.php, src/Resources/config/services.xml
* Solves 
#10 
* Description: Added language support which allows to export product feed using different language.
* PHP Version
7.4
* Shopware Version
6.3.5.1
=> FFWEB-1981: Add language support

src/Export/ExportProducts.php, src/Resources/config/services.xml
* Description
Allow user to define custom associations used for product data fetch. For instance product variants has not hydrated with the image covers  
* Tested with Shopware6 editions/versions:
6.4.0
* Tested with PHP versions:
7.4
=> FFWEB-2053: Adding custom associations

src/Resources/app/storefront/src/scss/_recommendation.scss, src/Resources/app/storefront/src/scss/base.scss, src/Resources/views/storefront/base.html.twig, src/Resources/views/storefront/page/product-detail/tabs.html.twig
Implement ff-recommendation on product detail page
=> FFWEB-2018: Add ff-recommendation tag to the product detail page

src/Resources/config/services.xml, src/Resources/views/storefront/base.html.twig, src/Subscriber/CategoryView.php, src/Subscriber/ConfigurationSubscriber.php
* Description
Implement login tracking, add possibility to pass custom constant communication parameters
* Tested with Shopware6 editions/versions:
6.4.0
* Tested with PHP versions:
7.4
=> FFWEB-2069: Use Personalization support

spec/Export/CurrencyFieldsProviderSpec.php, spec/Export/CustomFieldsServiceSpec.php, spec/Export/Field/CustomFieldsSpec.php, spec/Export/Field/PriceCurrencySpec.php, src/Command/ProductExportCommand.php, src/Export/CurrencyFieldsProvider.php, src/Export/CustomFieldsService.php, src/Export/Data/Entity/EntityFactory.php, src/Export/Field/CustomFields.php
Refactor services names and locations, add missing unit test for PriceCurrency
6.4
7.4
=> Refactor, add more unit tests

src/Resources/views/storefront/page/checkout/cart/index.html.twig, src/Resources/views/storefront/page/product-detail/tabs.html.twig
=> fix passing variables to twig templates

src/Command/CmsExportCommand.php, src/Command/ProductExportCommand.php, src/Export/Data/DataProvider.php, src/Export/Data/Entity/CategoryEntity.php, src/Export/Data/Entity/EntityFactory.php, src/Export/ExportCategories.php, src/Export/ExportInterface.php, src/Export/ExportProducts.php, src/Export/Feed.php, src/Export/FeedFactory.php, src/Export/Field/CMS/Description.php, src/Export/Field/CMS/FieldInterface.php, src/Export/Field/CMS/Keywords.php, src/Export/Field/CMS/Master.php, src/Export/Field/CMS/MetaTitle.php, src/Export/Field/CMS/Name.php, src/Export/Field/CMS/PageId.php, src/Export/Field/CMS/SeoPathInfo.php, src/OmikronFactFinder.php, src/Resources/config/services.xml
FFWEB-2123
Create CMS export Command
6.4.1.1 
7.4.20
=> FFWEB-2123: Create CMS export Command

src/Export/ExportCategories.php, src/Export/Field/CMS/CustomFields.php, src/OmikronFactFinder.php, src/Resources/config/services.xml
[FFWEB-2130](https://jira.omikron.net/browse/FFWEB-2130)
Create Additional FieldProviders
6.4.1.1
7.4.20
=> FFWEB-2130: Add FieldProviders

README.md
[FFWEB-2131](https://jira.omikron.net/browse/FFWEB-2131)
Add Documentation to CMS Export
6.4.1.1
7.4.20
=> FFWEB-2131: Add documentation

src/Command/BrandExportCommand.php
FFWEB-2135
Add Brand export command
6.4.1.1
7.4.20
=> FFWEB-2135: Add brand export command

README.md
FFWEB-2137
Update documentation
6.4.1.1
7.4.20
=> FFWEB-2137: Update README.md

CHANGELOG.md, README.md, src/Export/Data/Factory/FactoryInterface.php, src/Export/ExportBrands.php, src/Export/ExportCategories.php, src/Export/ExportInterface.php, src/Export/ExportProducts.php, src/Export/FeedFactory.php, src/Export/Field/FieldInterface.php, src/Resources/views/storefront/base.html.twig
Description: 
-  Prepare Changelog, 
- update README,
- Clean public interfaces
- add default filter to rendering communication parameters in base.html.twig
Tested with Shopware6 editions/versions: 
- 6.4
Tested with PHP versions: 
- 7.4
=> Prepare Release 2.0

CHANGELOG.md, src/Resources/app/storefront/src/scss/_asn.scss
=> FFWEB-2156: ASN styles causes wrong width of the document body

spec/Export/Field/ImageUrlSpec.php, src/Export/Field/ImageUrl.php
FFWEB-2187
Fix ImageProvider
6.4.1.1
7.4.20
=> FFWEB-2187: Fix ImageProvider

CHANGELOG.md, spec/Export/Field/CustomFieldsSpec.php, src/Export/Data/Factory/ProductEntityFactory.php, src/Export/Field/CustomFields.php, src/Internal/utils.php
Export failes on exporting CustomFields of type Entity. Both single selection and multi selection (different causes)
6.4.2.1
8.0
=> FFWEB-2323: CustomFields export error

CHANGELOG.md, spec/Export/Field/DeeplinkSpec.php, src/Export/FeedFactory.php, src/Export/Field/Deeplink.php, src/Internal/utils.php
Reindex product urls if during the export, they don't have seo url already indexed
6.4.2.1
7.4
=> FFWEB-2231: Generate missing SEO URLs

CHANGELOG.md, spec/Subscriber/CategoryPageSubscriberSpec.php, src/Resources/config/services.xml, src/Subscriber/CategoryPageSubscriber.php, src/Subscriber/ConfigurationSubscriber.php
FFWEB-2336
add params to configuration subscriber
6.2.4
7.4.20
=> FFWEB-2336: add params to configuration subscriber

CHANGELOG.md, spec/Export/ChannelTypeNamingStrategySpec.php, spec/Export/CurrencyFieldsProviderSpec.php, spec/Export/CustomFieldsServiceSpec.php, src/Command/DataExportCommand.php, src/Config/FtpConfig.php, src/Export/ChannelTypeNamingStrategy.php, src/Export/NamingStrategyInterface.php, src/Resources/config/services.xml, src/Upload/UploadService.php
Add unified feed naming 
6.4.9999999.9999999 Developer Version
- 8.0
=> FFWEB-2744: Fix provide unified way to naming feed files

CHANGELOG.md, src/Resources/views/storefront/components/factfinder/asn.html.twig
- FFWEB-2547
- Description:
- added facet label (name) to the chosen filter values (Filter cloud)
- 7.4
=> FFWEB-2547: added facet label (name) to the chosen filter values (Filter cloud)

src/Resources/views/storefront/base.html.twig
,so it can be extended in projects
=> add an twig block around the ff-communication tag

CHANGELOG.md, src/Resources/snippet/factfinder.de-DE.json, src/Resources/snippet/factfinder.en-GB.json, src/Resources/views/storefront/page/factfinder/result.html.twig
- FFWEB-2560
- Description:
- Add "You search for" on search result page
- 7.4
=> FFWEB-2560: Add "You search for" on search result page

src/Subscriber/ConfigurationSubscriber.php
- FFWEB-2565
- Description:
- fixed condition which assign default field roles
- 7.4
=> FFWEB-2565 - fixed condition which assign default field roles

CHANGELOG.md, src/Subscriber/BeforeSendResponseEventSubscriber.php
- FFWEB-2622
- Description:
- Fix error during activation
- 7.4
=> FFWEB-2622: Fix error during activation

CHANGELOG.md, spec/Subscriber/ConfigurationSubscriberSpec.php, src/Resources/views/storefront/base.html.twig, src/Subscriber/BeforeSendResponseEventSubscriber.php, src/Subscriber/CategoryPageSubscriber.php, src/Subscriber/ConfigurationSubscriber.php
- FFWEB-2622
- Description:
- Fix error during activation
- Fix search-immediate behaviour on Category Page
- 7.4
=> FFWEB-2622: Activation error and category page

README.md, composer.json, spec/Storefront/Controller/ResultControllerSpec.php, spec/Subscriber/CategoryPageSubscriberSpec.php, spec/Subscriber/ConfigurationSubscriberSpec.php, src/Config/Communication.php, src/Export/Field/CustomFields.php, src/Resources/config/config.xml, src/Resources/config/services.xml, src/Resources/views/storefront/base.html.twig, src/Resources/views/storefront/components/factfinder/record-list.html.twig, src/Resources/views/storefront/components/factfinder/record.html.twig, src/Resources/views/storefront/element/cms-element-record-list.html.twig, src/Resources/views/storefront/page/factfinder/result.html.twig, src/Storefront/Controller/ResultController.php, src/Subscriber/CategoryPageResponseSubscriber.php, src/Subscriber/CategoryPageSubscriber.php, src/Subscriber/ConfigurationSubscriber.php, src/Utilites/Ssr/PriceFormatter.php, src/Utilites/Ssr/SearchAdapter.php, src/Utilites/Ssr/Template/RecordList.php
- FFWEB-2524
- Description:
- Server-Side Rendering
- 7.4
=> FFWEB-2524: SSR

CHANGELOG.md, src/Resources/views/storefront/base.html.twig, src/Subscriber/CategoryPageResponseSubscriber.php, src/Utilites/Ssr/Template/RecordList.php
- FFWEB-2666
- Description:
- fixed search results when SSR enabled
- 6.4.18.0
- 7.4
- 8.1
=> FFWEB-2666 - fixed search results when SSR enabled

CHANGELOG.md, src/Api/UpdateFieldRolesController.php, src/Config/CachedFieldRoles.php, src/Config/FieldRoles.php, src/Config/FieldRolesInterface.php, src/Resources/config/services.xml, src/Utilites/Ssr/PriceFormatter.php, src/Utilites/Ssr/Template/Filter.php
- FFWEB-2686
- Description:
- Fix problem with "add to cart" tracking
- 6.4.18.0
- 7.4
- 8.1
=> FFWEB-2686: Cache field roles as they are searched for on every request

CHANGELOG.md, spec/Subscriber/ConfigurationSubscriberSpec.php, src/Resources/views/storefront/base.html.twig, src/Subscriber/ConfigurationSubscriber.php
- FFWEB-2690
- Description:
- Fix problem with new map due to SecurityExtension
- 6.4.20.0
- 8.2
=> FFWEB-2690: fix problem with new map due to SecurityExtension

CHANGELOG.md, src/Storefront/Controller/ResultController.php
- FFWEB-2692
- Description:
- Security patch
- 6.4.20.0
- 8.2
- 7.4
=> FFWEB-2692: Security patch

CHANGELOG.md, src/Resources/views/storefront/page/factfinder/result.html.twig
- FFWEB-2702
- Description:
- Fix problem with ff-template in search result page
- 6.4.20.0
- 8.2
- 7.4
=> FFWEB-2702 Fix problem with ff-template in search result page

CHANGELOG.md, src/Cookie/CookieProvider.php, src/Resources/snippet/factfinder.de-DE.json, src/Resources/snippet/factfinder.en-GB.json
- FFWEB-2746
- Description:
- Group 3 FactFinder cookies into one group
- 6.4.20.0
- 8.2
- 7.4
=> FFWEB-2746 Group 3 FactFinder cookies into one group

CHANGELOG.md, composer.json, src/Api/UiFeedExportController.php, src/Api/UpdateFieldRolesController.php, src/Command/DataExportCommand.php, src/Export/FtpAdapterFactory.php, src/Export/SftpAdapterFactory.php, src/Resources/config/config.xml, src/Resources/config/services.xml, src/Upload/UploadService.php
- Solves issue: FFWEB-2780
- Description: Rewrite FTP and SFTP connection
=> FFWEB-2780: Rewrite FTP and SFTP connection

CHANGELOG.md, spec/Subscriber/BeforeSendResponseEventSubscriberSpec.php, src/Resources/app/storefront/src/main.js, src/Resources/app/storefront/src/reacting-cookie/reacting-cookie.js, src/Resources/views/storefront/base.html.twig, src/Subscriber/BeforeSendResponseEventSubscriber.php
- Solves issue: FFWEB-2782
- Description: Fix save cookies into Shopware Cookie Consent Manager
=> FFWEB-2782: Fix save cookies into Shopware Cookie Consent Manager

CHANGELOG.md, README.md, src/Command/RunPreprocessorCommand.php, src/Resources/config/config.xml
- Solves issue: FFWEB-2783
- Description: Add documentation for SDK v5.x
=> FFWEB-2783: Add documentation for SDK v5.x

CHANGELOG.md, README.md, src/DataAbstractionLayer/FeedPreprocessor.php, src/Resources/config/services.xml, src/ScheduledTask/MarketplaceReportTask.php, src/ScheduledTask/MarketplaceReportTaskHandler.php
- Solves issue: FFWEB-2953
- Description: Add reporting for Shopware marketplace
- Tested with Shopware6 editions/versions: 6.5.5
=> FFWEB-2953: Add reporting for Shopware marketplace

spec/Export/ChannelTypeNamingStrategySpec.php, spec/Export/Field/DeeplinkSpec.php, src/Api/UpdateFieldRolesController.php, src/FactFinder.php
- Solves issue: FFWEB-2989
- Description: Export deeplink improvements
- Tested with PHP versions: 8.2
=> FFWEB-2989: Export deeplink improvements

.scannerwork/report-task.txt, src/Command/DataExportCommand.php, src/Export/Data/Factory/ProductEntityFactory.php, src/Export/Field/Deeplink.php, src/Resources/views/storefront/base.html.twig, src/Resources/views/storefront/components/factfinder/record-list-slider.html.twig, src/Upload/UploadService.php
- Solves issue: FFWEB-2991
- Description: Prepare Plugin for marketplace review
=> FFWEB-2991: Prepare Plugin for marketplace review

CHANGELOG.md, src/Storefront/Controller/ResultController.php, src/Subscriber/CategoryPageResponseSubscriber.php, src/Utilites/Ssr/Exception/DetectRedirectCampaignException.php, src/Utilites/Ssr/Template/RecordList.php
- Solves issue: FFWEB-2997
- Description: Support Fact-Finder redirect campaigns for SSR
=> FFWEB-2997: Support Fact-Finder redirect campaigns for SSR

src/Api/UpdateFieldRolesController.php, src/Command/DataExportCommand.php, src/Resources/app/administration/src/module/sw-cms/snippet/en-GB.json, src/Resources/config/services.xml, src/Subscriber/CategoryPageResponseSubscriber.php
- Solves issue: FFWEB-3009
- Description: Get rid of default context and container
- Tested with PHP versions: 8.2
=> FFWEB-3009: Get rid of default context and container

CHANGELOG.md, composer.json, spec/Subscriber/CategoryPageSubscriberSpec.php, src/Subscriber/CategoryPageSubscriber.php, src/Subscriber/ConfigurationSubscriber.php
- Solves issue: FFWEB-3041
- Description: Handle category-page for ff-communication
=> FFWEB-3041: Handle category-page for ff-communication

CHANGELOG.md, src/Resources/views/storefront/base.html.twig, src/Storefront/Controller/ResultController.php
- Solves issue: FFWEB-3044:
- Description: Support sid for SSR
=> FFWEB-3044: Support sid for SSR
